### ISSUE TITLE
Cancellable `Decoder.Parse`

### ISSUE THREAD

**Issue by iulian-gm** [thomersch/gosmparse#5]
Perhaps I am missing some functionality, but wouldn't it be helpful if `Parse` took a context so that it can be cancelled? Currently the only way to stop the parsing is to panic. It would be good to be able to gracefully terminate the parsing as it is a long running task.

**Comment by thomersch** [comment]
Thank you for reporting!

You are right, `Parse` is not cancelable, but I do think it would be feasible to do this. I struggle to understand the use case: Why should one decide to stop parsing a file? If you‘re reading from a stream, you could just close it and the reader would run dry.

If we‘d start passing context into the process, a user would probably expect that we’d pass it onto the Node/Way/Relation emitters which would have a significant overhead.

PRs are welcome anyway. If you submit one, please make sure that it doesn‘t break existing interfaces and doesn‘t degrade performance for existing code.

**Comment by thomersch** [comment]
If anyone needs this and wants to implement it, patches welcome!

I‘ll close here since I don‘t need it and won‘t implement it myself.
